[package]
name = "raylib-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "raylib"
crate-type = ["rlib", "cdylib"]

[dependencies]
glam = "0.33"
sdl3-sys = { version = "0.7.1", features = []}
gl = "0.14.0"
log = { version = "0.4" }
env_logger = { version = "0.11" }
strum = "0.28"
strum_macros = "0.28"
image = { version = "0.25.10", default-features = false } # todo: re-export more configurable feature flags
swash = { version = "0.2.10"}

[features]
default = ["DESKTOP_DEFAULTS"]

# look in raylib config.h and make sure they match for reasonably good defaults
DESKTOP_DEFAULTS = [
    "GRAPHICS_API_OPENGL_33", 
    "SUPPORT_WINMM_HIGHRES_TIMER", 
    "SUPPORT_PARTIALBUSY_WAIT_LOOP", 
    "SUPPORT_MODULE_RTEXT",
    "SUPPORT_MODULE_RSHAPES",
    "SUPPORT_FILEFORMAT_BMP", 
    "SUPPORT_FILEFORMAT_PNG", 
    "SUPPORT_FILEFORMAT_JPG",
    "SUPPORT_SCREEN_CAPTURE"
]

ANDROID_DEFAULTS = [
    "GRAPHICS_API_OPENGL_ES3", 
    "PLATFORM_ANDROID",
    "SUPPORT_PARTIALBUSY_WAIT_LOOP", 
    "SUPPORT_MODULE_RTEXT",
    "SUPPORT_MODULE_RSHAPES",
    "SUPPORT_FILEFORMAT_BMP", 
    "SUPPORT_FILEFORMAT_PNG", 
    "SUPPORT_FILEFORMAT_JPG",
    "SUPPORT_SCREEN_CAPTURE",
]

GRAPHICS_API_OPENGL_33 = []
GRAPHICS_API_OPENGL_43 = ["GRAPHICS_API_OPENGL_33"]
GRAPHICS_API_OPENGL_ES2 = []
GRAPHICS_API_OPENGL_ES3 = ["GRAPHICS_API_OPENGL_ES2"]
RLGL_SHOW_GL_DETAILS_INFO = [] # prints all loaded extensions,etc, very verbose

PLATFORM_ANDROID = []
PLATFORM_DESKTOP_SDL = []
SUPPORT_AUTOMATION_EVENTS = []
SUPPORT_BUSY_WAIT_LOOP = []
SUPPORT_CAMERA_SYSTEM = []
SUPPORT_COMPRESSION_API = []
SUPPORT_CUSTOM_FRAME_CONTROL = []
SUPPORT_GESTURES_SYSTEM = []
SUPPORT_MODULE_RAUDIO = []
SUPPORT_MODULE_RMODELS = []
SUPPORT_MODULE_RSHAPES = []
SUPPORT_MODULE_RTEXT = []
SUPPORT_MOUSE_GESTURES = []
SUPPORT_PARTIALBUSY_WAIT_LOOP = []
SUPPORT_RPRAND_GENERATOR = []
SUPPORT_SCREEN_CAPTURE = [] # bound to f12 by default
SUPPORT_TRACELOG = []
SUPPORT_WINMM_HIGHRES_TIMER = [] # use high res timer on windows, on other platforms it has no effect
SUPPORT_CLIPBOARD_IMAGE = []
SUPPORT_FILEFORMAT_BMP = ["image/bmp"]
SUPPORT_FILEFORMAT_PNG = ["image/png"]
SUPPORT_FILEFORMAT_JPG = ["image/jpeg"]
SUPPORT_SPLINE_MITERS = []
SUPPORT_SPLINE_SEGMENT_CAPS = []
NO_DL_SDL = []
BUILD_SDL_FROM_SOURCE = ["sdl3-sys/build-from-source"]
SDL_NO_LINK = ["sdl3-sys/no-link"]

 # multithreading but image recommends library crates optionally enable this
IMAGE_RAYON = ["image/rayon"]
[build-dependencies]
