[package]
name = "raylib-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.27"
sdl3 = { version = "0.18.3", features = ["use-pkg-config"] }
libc = "0.2"
gl = "0.14.0"
log = { version = "0.4" }
env_logger = { version = "0.11" }
strum = "0.28"
strum_macros = "0.28"

[features]
default = ["opengl_33"]
opengl_33 = []
opengl_43 = []
opengl_es3 = []
gles2 = []
RLGL_SHOW_GL_DETAILS_INFO = []

[build-dependencies]
cc = "1.0"
bindgen = "0.69"
